# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cb13b22702f968b39700199a8dd4fdc14c14578cb60458ac428903a35bd0b34c5879385bb8f146a2ed72c5cd4498edf918f335300bf9a5d47160eeac3441052

test:
  secret_key_base: 04e48658f8545c77417e0932eed7280e7ea69574351f627367966d1038843869054cc7d8bcca26cd8cb7452b4bc9e347f9e9c036d1cc398af9c0f979ad9553a7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
